-- Database: GLOBALPLA Metadata version: 2 Exported: Feb 24, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6637_DOL_LMT" USING 'GCG_6637_DOL_LMT.mkd' PAGESIZE=4096 (
 "GS_USER" VARCHAR(8) NOT NULL,
 "AMOUNT_LIMIT" NUMERIC(15,2) NOT NULL,
 "PL_LIMIT" VARCHAR(200) NOT NULL,
 "APPROVER" CHAR(8) );
-- End Multi-Line Statement
ALTER TABLE "GCG_6637_DOL_LMT" ADD CONSTRAINT "PK_GS_USER" PRIMARY KEY  ( "GS_USER", "AMOUNT_LIMIT", "PL_LIMIT" ) USING 0;
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
